[package]
name = "rust-mutex-perf-test"
version = "0.1.0"
authors = ["Matt Jurik <exabytes18@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
